# Generated by Django 3.1 on 2020-08-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgregarUsuarios', '0002_auto_20200811_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=30)),
                ('roll', models.CharField(max_length=25, verbose_name='rol')),
                ('usuario_activo', models.BooleanField(default=False)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
