# Generated by Django 3.1 on 2020-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgregarUsuarios', '0003_auto_20200811_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
    ]
